name: Build ComfyUI

on:
  # push:
  # delete:
  # create:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: '0 16 * * 0'

jobs:
  Build-ComfyUI:
    name: Build ComfyUI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enter Workspace
        shell: pwsh
        run: |
          Set-Location -Path "${{ github.workspace }}"

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Launch ComfyUI Installer
        shell: pwsh
        run: |
          & "${{ github.workspace }}/comfyui_installer.ps1" `
            -InstallPath "${{ github.workspace }}/comfyui" `
            -BuildMode `
            -BuildWithUpdate `
            -BuildWithUpdateNode `
            -BuildWithLaunch `
            -BuildWithTorch 31 `
            -DisablePipMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror `
            -NoPreDownloadModel

      - name: Install Hanamizuki
        shell: pwsh
        run: |
          . "${{ github.workspace }}/comfyui/activate.ps1"
          Install-Hanamizuki

      - name: Make docs
        shell: pwsh
        run: |
          python "${{ github.workspace }}/.github/make_docs.py" "${{ github.workspace }}/comfyui"

      - name: Make configure env script
        shell: pwsh
        run: |
          Copy-Item -Path "${{ github.workspace }}/configure_env.bat" -Destination "${{ github.workspace }}/comfyui/configure_env.bat" -Force

      - name: Archive
        shell: pwsh
        run: |
          $build_time = (Get-Date).ToString("yyyyMMdd")
          $package_name = "comfyui_licyk_${build_time}"
          $protable_name = "${package_name}_nightly.7z"
          New-Item -ItemType Directory -Path "${{ github.workspace }}/sdnote/portable/nightly" -Force
          Move-Item -Path "${{ github.workspace }}/comfyui" -Destination "${{ github.workspace }}/${package_name}" -Force
          7z a -t7z "${{ github.workspace }}/sdnote/portable/nightly/comfyui/${protable_name}" "${{ github.workspace }}/${package_name}"

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: comfyui_nightly
          path: ${{ github.workspace }}/sdnote/portable/nightly/

      - name: Install HuggingFace library
        shell: pwsh
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          pip install huggingface_hub modelscope

      - name: Upload to HuggingFacee repo
        shell: python
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          import os
          from huggingface_hub import upload_large_folder

          upload_large_folder(
            repo_id="licyk/sdnote",
            repo_type="model",
            folder_path=os.path.join(os.environ.get("WORKSPACE"), "sdnote")
          )

      - name: Upload to ModelScope repo
        shell: python
        env:
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          import os
          from modelscope.hub.api import HubApi

          api = HubApi()
          api.login(os.environ.get("MODELSCOPE_API_TOKEN"))

          api.upload_folder(
              repo_id="licyks/sdnote",
              repo_type="model",
              folder_path=os.path.join(os.environ.get("WORKSPACE"), "sdnote")
          )
