name: Build SD-Trainer

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_sd_trainer.yml"
  # delete:
  # create:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: '30 17 * * 0'
  workflow_dispatch:

jobs:
  Build-SD-Trainer:
    name: Build SD-Trainer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Install fake nvidia-smi
        shell: pwsh
        run: |
          Copy-Item -Path "${{ github.workspace }}/.github/nvidia-smi.bat" -Destination "C:/Program Files/Git/cmd/nvidia-smi.bat" -Force

      - name: Launch SD-Trainer Installer
        shell: pwsh
        env:
          UV_NO_PROGRESS: 1
        run: |
          & "${{ github.workspace }}/sd_trainer_installer.ps1" `
            -InstallPath "${{ github.workspace }}/sd_trainer" `
            -BuildMode `
            -BuildWithUpdate `
            -BuildWithLaunch `
            -BuildWitchBranch 1 `
            -InstallBranch "sd_trainer" `
            -DisablePyPIMirror `
            -DisableGithubMirror `
            -InstallHanamizuki `
            -DisableHuggingFaceMirror

      - name: Make docs
        shell: pwsh
        run: |
          python "${{ github.workspace }}/.github/make_docs.py" "${{ github.workspace }}/sd_trainer"

      - name: Archive
        shell: pwsh
        run: |
          & "${{ github.workspace }}/.github/archive_portable.ps1" `
            -SoftwareName "sd_trainer" `
            -Workspace "${{ github.workspace }}" `
            -Source "${{ github.workspace }}/sd_trainer" `
            -SaveDst "${{ github.workspace }}/sdnote/portable/nightly" `
            -Author "licyk"

      - name: Install HuggingFace and ModelScope library
        shell: pwsh
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          pip install huggingface_hub modelscope

      - name: Upload to HuggingFace repo
        shell: pwsh
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/huggingface_release.py"

      - name: Upload to ModelScope repo
        shell: pwsh
        env:
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/modelscope_release.py"
