name: Build SD WebUI

on:
  push:
  delete:
  create:

jobs:
  Build-SD-WebUI:
    name: Build SD WebUI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enter Workspace
        shell: pwsh
        run: |
          Set-Location -Path "${{ github.workspace }}"

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Launch SD WebUI Installer
        shell: pwsh
        run: |
          & "${{ github.workspace }}/stable_diffusion_webui_installer.ps1" -InstallPath "${{ github.workspace }}/sd_webui_forge" -BuildMode -BuildWithUpdate -BuildWithUpdateNode -BuildWithLaunch -BuildWithTorch 0 -BuildWitchBranch 3 -InstallBranch "sd_webui_forge" -NoPreDownloadModel
