name: Build SD Scripts

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_sd_scripts.yml"
  # delete:
  # create:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: '15 17 * * 0'

jobs:
  Build-SD-Scripts:
    name: Build SD Scripts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enter Workspace
        shell: pwsh
        run: |
          Set-Location -Path "${{ github.workspace }}"

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Launch SD-Trainer-Script Installer
        shell: pwsh
        run: |
          & "${{ github.workspace }}/sd_trainer_script_installer.ps1" `
            -InstallPath "${{ github.workspace }}/sd_scripts" `
            -BuildMode `
            -BuildWithUpdate `
            -BuildWithLaunch `
            -BuildWitchBranch 2 `
            -InstallBranch "sd_scripts" `
            -DisablePipMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror `
            -PyTorchPackage "torch==2.6.0+cu124 torchvision==0.21.0+cu124 torchaudio==2.6.0+cu124" `
            -xFormersPackage "xformers==0.0.29.post3"

      - name: Make docs
        shell: pwsh
        run: |
          python "${{ github.workspace }}/.github/make_docs.py" "${{ github.workspace }}/sd_scripts"

      - name: Archive
        shell: pwsh
        run: |
          $build_time = (Get-Date).ToUniversalTime().AddHours(8).ToString("yyyyMMdd")
          $package_name = "sd_scripts_licyk_${build_time}"
          $protable_name = "${package_name}_nightly.7z"
          New-Item -ItemType Directory -Path "${{ github.workspace }}/sdnote/portable/nightly" -Force
          Move-Item -Path "${{ github.workspace }}/sd_scripts" -Destination "${{ github.workspace }}/${package_name}" -Force
          7z a -t7z -bsp1 "${{ github.workspace }}/sdnote/portable/nightly/sd_scripts/${protable_name}" "${{ github.workspace }}/${package_name}"

      - name: Install HuggingFace / ModelScope library
        shell: pwsh
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          pip install huggingface_hub modelscope

      - name: Upload to HuggingFace repo
        shell: pwsh
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/huggingface_release.py"

      - name: Upload to ModelScope repo
        shell: pwsh
        env:
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/modelscope_release.py"
