name: Build ComfyUI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_comfyui.yml"
  # delete:
  # create:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: '0 16 * * 0'

jobs:
  Build-ComfyUI:
    name: Build ComfyUI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Launch ComfyUI Installer
        shell: pwsh
        env:
          UV_NO_PROGRESS: 1
        run: |
          & "${{ github.workspace }}/comfyui_installer.ps1" `
            -InstallPath "${{ github.workspace }}/comfyui" `
            -BuildMode `
            -BuildWithUpdate `
            -BuildWithUpdateNode `
            -BuildWithLaunch `
            -DisablePyPIMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror `
            -NoPreDownloadModel `
            -PyTorchPackage "torch==2.6.0+cu124 torchvision==0.21.0+cu124 torchaudio==2.6.0+cu124" `
            -xFormersPackage "xformers==0.0.29.post3"

      - name: Launch ComfyUI to init custom nodes
        shell: pwsh
        env:
          PIP_NO_WARN_SCRIPT_LOCATION: 0
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          Set-Location -Path "${{ github.workspace }}/comfyui"
          & "${{ github.workspace }}/comfyui/python/python.exe" "${{ github.workspace }}/comfyui/ComfyUI/main.py" --quick-test-for-ci --cpu

      - name: Launch to complete dependencies
        shell: pwsh
        env:
          UV_NO_PROGRESS: 1
        run: |
          & "${{ github.workspace }}/comfyui/launch.ps1" `
            -BuildMode `
            -DisablePyPIMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror

      - name: Install Hanamizuki
        shell: pwsh
        run: |
          . "${{ github.workspace }}/comfyui/activate.ps1"
          Install-Hanamizuki

      - name: Make docs
        shell: pwsh
        run: |
          python "${{ github.workspace }}/.github/make_docs.py" "${{ github.workspace }}/comfyui"

      - name: Archive
        shell: pwsh
        run: |
          $build_time = (Get-Date).ToUniversalTime().AddHours(8).ToString("yyyyMMdd")
          $package_name = "comfyui_licyk_${build_time}"
          $protable_name = "${package_name}_nightly.7z"
          New-Item -ItemType Directory -Path "${{ github.workspace }}/sdnote/portable/nightly" -Force
          Move-Item -Path "${{ github.workspace }}/comfyui" -Destination "${{ github.workspace }}/${package_name}" -Force
          7z a -t7z -bsp1 "${{ github.workspace }}/sdnote/portable/nightly/comfyui/${protable_name}" "${{ github.workspace }}/${package_name}"

      - name: Install HuggingFace library
        shell: pwsh
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          pip install huggingface_hub modelscope

      - name: Upload to HuggingFace repo
        shell: pwsh
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/huggingface_release.py"

      - name: Upload to ModelScope repo
        shell: pwsh
        env:
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          python "${{ github.workspace }}/.github/modelscope_release.py"
