name: Build Fooocus

on:
  push:
  # delete:
  create:

jobs:
  Build-Fooocus:
    name: Build Fooocus
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enter Workspace
        shell: pwsh
        run: |
          Set-Location -Path "${{ github.workspace }}"

      - name: List files in the repository
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Launch Fooocus Installer
        shell: pwsh
        run: |
          & "${{ github.workspace }}/fooocus_installer.ps1" `
            -InstallPath "${{ github.workspace }}/fooocus" `
            -BuildMode `
            -BuildWithUpdate `
            -BuildWithLaunch `
            -BuildWithTorch 32 `
            -BuildWitchBranch 3 `
            -InstallBranch "fooocus" `
            -DisablePipMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror

      # - name: Archive
      #   shell: pwsh
      #   run: |
      #     7z a -t7z "${{ github.workspace }}/artifact/sd_webui_forge_nightly_cu126.7z" "${{ github.workspace }}/sd_webui_forge"

      # - name: Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sd_webui_forge_nightly
      #     path: ${{ github.workspace }}/artifact/
